/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.GestorUsuario;
import dto.UsuarioDTO;
import messages.Util;
import dto.UsuarioDTO;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import messages.Util;

/**
 *
 * @author estan
 */
public class Inicio extends javax.swing.JFrame {

    GestorUsuario gestorUsuario = new GestorUsuario();
    
    //Bordes de los TXT y del Box para pintarlos
    Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
    Border originalTXTBorder;
    Border originalBOXBorder;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        //Inicializacion de los bordes originales
       originalTXTBorder  = txtNroDocumento.getBorder();
       originalBOXBorder = boxRol.getBorder();
    }
    
    
    //Funcion para comprobar que un string es un numero
    public boolean isInteger(String numero){
        try{
            Integer.parseInt(numero);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }
    
    
    //Funcion que pinta de rojo los TXT y el Box en caso de que sena invalidos
    public void pintarInvalidos(String nroDocumento, String contrasenia, boolean no_esta){
        if(nroDocumento.isEmpty() || !isInteger(nroDocumento)|| no_esta){
            txtNroDocumento.setBorder(redBorder);
        } else {
            txtNroDocumento.setBorder(originalTXTBorder);
        }
        if(contrasenia.isEmpty() || no_esta){
            txtContrasenia.setBorder(redBorder);
        } else {
            txtContrasenia.setBorder(originalTXTBorder);
        }
        if(no_esta){
            boxRol.setBorder(redBorder);
        } else{
            boxRol.setBorder(originalBOXBorder);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_Documento = new javax.swing.JLabel();
        txtNroDocumento = new javax.swing.JTextField();
        jLabel_Contrasenia = new javax.swing.JLabel();
        jLabel_Contrasenia1 = new javax.swing.JLabel();
        boxRol = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        txtContrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Inicio de Sesión");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel_Documento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Documento.setText("Nro. de Documento");

        jLabel_Contrasenia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Contrasenia.setText("Contraseña");

        jLabel_Contrasenia1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Contrasenia1.setText("Rol:");

        boxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPERADOR", "ADMINISTRADOR" }));
        boxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRolActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNroDocumento)
                            .addComponent(jLabel_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Contrasenia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtContrasenia))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel_Documento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Contrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Contrasenia1)
                    .addComponent(boxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRolActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        //Obtenemos los valores
        String nroDocumento = (String) txtNroDocumento.getText();
        String contrasenia = new String(txtContrasenia.getPassword());
        String rol = (String) boxRol.getSelectedItem();

        //Corroboramos que no esten vacios
        if(nroDocumento.isEmpty() || contrasenia.isEmpty()){
            pintarInvalidos(nroDocumento, contrasenia, false);
            Util.mensajeAdvertencia("Advertencia", "No se permiten campo/s vacío/s");
        //Corroboramos que solo haya numeros en nroDocumento
        } else if (!isInteger(nroDocumento)){
            pintarInvalidos(nroDocumento, contrasenia, false);
            Util.mensajeAdvertencia("Advertencia", "Formato invalido");
        } else {    
            //Buscamos el usuario con ese nroDocumento, contrasenia y rol
            try {
                UsuarioDTO usuarioDTO = gestorUsuario.buscarUsuario(nroDocumento, contrasenia, rol);
                if(usuarioDTO != null){
                    //Abrir menu principal ACA
                } else {
                    Util.mensajeAdvertencia("Advertencia", "Nro. de documento, contraseña o rol incorrectos");
                    pintarInvalidos(nroDocumento, contrasenia, true);
                }
            } catch (Exception e) {
                Util.mensajeError("Error", "Error al conectar en la base de datos");
            }
        }
            
            
        
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRol;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Contrasenia;
    private javax.swing.JLabel jLabel_Contrasenia1;
    private javax.swing.JLabel jLabel_Documento;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtNroDocumento;
    // End of variables declaration//GEN-END:variables
}
